apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbaas101
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaas101
rules:
- apiGroups:
  - pingcap.com
  resources:
  - tidbclusters
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dbaas101
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dbaas101
subjects:
- kind: ServiceAccount
  name: dbaas101
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbaas101
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: dbaas101
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dbaas101
    spec:
      containers:
      - args:
        - --api-bind-address=:8082
        command:
        - /dbaas101
        image: <your image url>
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: dbaas101
        ports:
        - containerPort: 8082
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceAccount: dbaas101
      serviceAccountName: dbaas101
